- name: Copy proxy real ip snippet
  copy:
    src: proxy_real_ip
    dest: /usr/local/etc/nginx/snippets/proxy_real_ip
  notify:
    - Reload nginx

- name: Create http proxy config
  template:
    src: ipv4_http_proxy.j2
    dest: /usr/local/etc/nginx/ipv4_http_proxy.conf
  notify:
    - Reload nginx

- name: Create https proxy config
  template:
    src: ipv4_https_proxy.j2
    dest: /usr/local/etc/nginx/ipv4_https_proxy.conf
  notify:
    - Reload nginx
