all:
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    remote_monit_host: blacky.dyn.a0s.de
    jailed: false
    jail_host: null
  children:

    jail_hosts:
      vars:
        ansible_become: true
      hosts:
        blacky.dyn.a0s.de:

    jails:
      vars:
        jailed: true
        ansible_user: root
      children:

        blacky:
          hosts:
            ansible-sandbox.dyn.a0s.de:
          vars:
            jail_host: blacky.dyn.a0s.de
