all:
  children:

    jail_hosts:
      hosts:
        hope.a0s.de:
        claude.a0s.de:
        blacky.dyn.a0s.de:
        sandy.dyn.a0s.de:

    jails:
      children:

        hope_jails:
          # hosts:

        claude_jails:
          hosts:
            ns2.a0s.de:

        blacky_jails:
          # hosts:

        sandy_jails:
          # hosts:

    nsd_servers:
      hosts:
        ns2.a0s.de:
