all:
  children:
    jail_hosts:
      hosts:
        blacky.dyn.a0s.de:

      vars:
        ansible_become: true

    jails:
      children:

        blacky:
          hosts:
            ansible-sandbox.dyn.a0s.de:
          vars:
            jail_host: blacky.dyn.a0s.de

      vars:
        ansible_user: root

  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    remote_monit_host: blacky.dyn.a0s.de
