all:
  children:
    jails:
      children:

        blacky:
          hosts:
            ansible-sandbox.dyn.a0s.de:
          vars:
            jail_host: blacky.dyn.a0s.de

      vars:
        jailed: true
        ansible_user: root

  vars:
    ansible_python_interpreter: /usr/local/bin/python3
