- hosts: jail_hosts
  roles:
    - pf
    - monit
    - zsh

- hosts: jails
  gather_facts: no
  roles:
    - jail

- hosts: jails
  roles:
    - zsh
  vars:
    zsh_theme: bira

- hosts: nsd_servers
  roles:
    - nsd

- hosts: hope.a0s.de
  roles:
    - nginx

- hosts: claude.a0s.de
  roles:
    - nginx

- hosts: blacky.dyn.a0s.de
  roles:
    - monit
