- hosts: jail_hosts
  roles:
    - pf
    - monit

- hosts: nsd_servers
  roles:
    - nsd

- hosts: hope.a0s.de
  roles:
    - nginx

- hosts: claude.a0s.de
  roles:
    - nginx

- hosts: blacky.dyn.a0s.de
  roles:
    - monit
