- hosts: jail_hosts
  roles:
    - name: monit

- hosts: ansible-sandbox.dyn.a0s.de
  roles:
    - name: nginx
      servers:
        - name: testy.ansible-sandbox.dyn.a0s.de
          tls: true
          www_subdomain: true
