- hosts: jail_hosts
  roles:
    - name: monit

- hosts: jails
  tasks:
    - name: Set jail name
      set_fact:
        jailed: true
        jail_name: '{{ ansible_hostname|replace("-", "_") }}'

- hosts: blacky.dyn.a0s.de
  roles:
    - name: nginx
      proxy_ipv4:
        - host: ansible-sandbox.dyn.a0s.de
          names:
            - testy.ansible-sandbox.dyn.a0s.de
            - www.testy.ansible-sandbox.dyn.a0s.de

- hosts: ansible-sandbox.dyn.a0s.de
  roles:
    - name: nginx
      servers:
        - name: testy.ansible-sandbox.dyn.a0s.de
          tls: true
          www_subdomain: true
      remote_monit: true
      remote_monit_skip_ipv4: true
