- hosts: jail_hosts
  roles:
    - pf
    - monit

- hosts: blacky.dyn.a0s.de
  roles: []

- hosts: ansible-sandbox.dyn.a0s.de
  roles:
    - nginx

- hosts: jails
  gather_facts: no
  roles:
    - jail

- hosts: jails
  roles:
    - zsh
  vars:
    zsh_theme: bira
