- hosts: jail_hosts
  roles:
    - base
    - pf
    - monit
    - zsh

- hosts: blacky.dyn.a0s.de
  roles: []

- hosts: jails
  gather_facts: no
  roles:
    - jail

- hosts: jails
  roles:
    - base
    - zsh
  vars:
    zsh_theme: bira
