- name: gather facts from db servers
  setup:
  delegate_to: '{{ item }}'
  delegate_facts: true
  loop: '{{ groups[inventory_hostname_short + "_jails"] }}'

- name: Add IPv6 host to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ':.*{{ hostvars[item].inventory_hostname }}'
    line: "{{ hostvars[item].ansible_all_ipv6_addresses[0] }}\t{{ hostvars[item].inventory_hostname }}"
  with_items: '{{ groups[inventory_hostname_short + "_jails"] }}'
  notify:
    - Reload pf

- name: Add IPv4 host to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '\..*{{ hostvars[item].inventory_hostname }}'
    line: "{{ hostvars[item].ansible_all_ipv4_addresses[0] }}\t{{ hostvars[item].inventory_hostname }}"
  when: hostvars[item].ansible_all_ipv4_addresses|length > 0
  with_items: '{{ groups[inventory_hostname_short + "_jails"] }}'
  notify:
    - Reload pf

- name: Create pf.conf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
  notify:
    - Reload pf
