- name: Install nsd
  pkgng:
    name: nsd
    state: present
  notify:
    - Start nsd

- name: Create main config
  template:
    src: nsd.conf.j2
    dest: /usr/local/etc/nsd/nsd.conf
  notify:
    - Reconfig nsd

- name: Create zones directory
  file:
    name: /usr/local/etc/nsd/zones
    state: directory

- name: Setup nsd-control
  command: /usr/local/sbin/nsd-control-setup
  args:
    creates: /usr/local/etc/nsd/nsd_control.pem

- name: Create zonefiles
  template:
    src: zonefile.zone.j2
    dest: '/usr/local/etc/nsd/zones/{{ item.name }}.zone'
  with_items: '{{ nsd_zones|selectattr("locally_managed", false, false) }}'
  when: 'nsd_role == "master"'
  notify:
    - Reload nsd

- name: Create locally managed zonefiles
  file:
    path: '/usr/local/etc/nsd/zones/{{ item.name }}.zone'
    state: touch
  with_items: '{{ nsd_zones|selectattr("locally_managed", true, false) }}'
  when: 'nsd_role == "master"'
  notify:
    - Reload nsd
