jail_name: ansible-sandbox

nginx_servers:
  - name: testy.ansible-sandbox.dyn.a0s.de
    tls: true
    www_subdomain: true
    root: testy
    proxy_ipv4: true
    monit_remote: false
    monit_remote_skip_ipv4: true
    monit_remote_target_status_code: 404
